NWDNuGet/NWDWebGitLabReport/Controllers/NWDGitLabReportController.cs
using GitLabApiClient;
using GitLabApiClient.Models.Issues.Requests;
using Microsoft.AspNetCore.Mvc;
using NWDFoundation.Logger;
using NWDWebGitLabReport.Configuration;
using NWDWebGitLabReport.Models;
using NWDWebRuntime.Controllers;
using NWDWebStandard.Controllers;

namespace NWDWebGitLabReport.Controllers
{
    public class NWDGitLabReportController : NWDBasicController<NWDGitLabReportController>
    {
        //GET: /<controller>/
        //[HttpGet]
        //public async Task<IActionResult> ViewSecretToken(GitLabProjectModel sModel)
        //{
        //    string tSecretToken = string.Empty;
        //    string param1 = HttpUtility.ParseQueryString(HttpContext.Request.Query).Get("param1");
        //    if (string.IsNullOrEmpty(tSecretToken) == false)
        //    {
        //        NWDGitLabMilestonesListModel tGitLabMilestoneList = await NWDGitLabMilestonesListModel.Prepare(tSecretToken);
        //        ViewData.Add(nameof(NWDGitLabMilestonesListModel), tGitLabMilestoneList);
        //    }
        //    return View(ViewsConstants.ViewsPath<NWDGitLabReportController>("Index"));
        //}
        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> View(NWDProjectGitConnection sModel)
        {
            try
            {
                NWDGitLabMilestonesListModel tGitLabMilestoneList = await NWDGitLabMilestonesListModel.Prepare(sModel.LocalTokenReport,HttpContext);
                ViewData.Add(nameof(NWDGitLabMilestonesListModel), tGitLabMilestoneList);
                NWDProjectGitConnection? tModel = NWDWebGitLabReportConfiguration.KConfig.GetBySecretToken(sModel.LocalTokenReport);
                if (tModel != null)
                {
                    ViewData.Add(nameof(NWDProjectGitConnection), tModel);
                    ViewData.Add("Title", tModel.Name);
                }
            }
            catch (Exception tException)
            {
                NWDLogger.Exception(tException);
                return View("/Views/Shared/_Error.cshtml");
            }
            return View("/Views/NWDGitLabReport/Index.cshtml");
        }

        [HttpGet]
        [HttpPost]
        public async Task<IActionResult> ViewLastReport()
        {
            // NWDLogger.WriteLine(nameof(ViewLastReport));

            List<NWDProjectGitConnection> tList = NWDWebGitLabReportConfiguration.KConfig.Repositories;

            List<NWDGitLabMilestoneModel> tGitLabMilestoneModelList = new List<NWDGitLabMilestoneModel>();

            foreach (NWDProjectGitConnection tGit in tList)
            {
                // NWDLogger.WriteLine(tGit.GitProject);
                GitLabClient tGitlabClient = new GitLabClient(tGit.GitUrl, tGit.GitToken);
                var tMilestones = await tGitlabClient.Projects.GetMilestonesAsync(tGit.GitProject);
                foreach (GitLabApiClient.Models.Milestones.Responses.Milestone tM in tMilestones)
                {
                    // NWDLogger.WriteLine(tM.Title);
                    NWDGitLabMilestoneModel tGitLabMilestoneModel = new NWDGitLabMilestoneModel();
                    tGitLabMilestoneModel.Name = tM.Title;
                    tGitLabMilestoneModel.SecretToken = tGit.LocalTokenReport;
                    if (string.IsNullOrEmpty(tM.StartDate) == false)
                    {
                        tGitLabMilestoneModel.Start = DateTime.Parse(tM.StartDate);
                    }
                    if (string.IsNullOrEmpty(tM.DueDate) == false)
                    {
                        tGitLabMilestoneModel.Due = DateTime.Parse(tM.DueDate);
                    }
                    if (tGitLabMilestoneModel.Start <= DateTime.Now && tGitLabMilestoneModel.Due >= DateTime.Now)
                    {
                        //NWDLogger.WriteLine("I ADD MILESTONES " + tGitLabMilestoneModel.Name);
                        await tGitLabMilestoneModel.Prepare(tGit.LocalTokenReport, null, null);
                        tGitLabMilestoneModel.GitLabProject = tGit;
                        tGitLabMilestoneModelList.Add(tGitLabMilestoneModel);
                    }

                }
            }

            ViewData.Add(nameof(NWDGitLabMilestoneModel), tGitLabMilestoneModelList);
            return View("/Views/NWDGitLabReport/Index.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Index(NWDGitLabMilestoneModel sGitLabMilestone)
        {
            NWDProjectGitConnection? tModel = NWDWebGitLabReportConfiguration.KConfig.GetBySecretToken(sGitLabMilestone.SecretToken);
            if (tModel != null)
            {
                ViewData.Add("Title", tModel.Name);

                if (sGitLabMilestone.IssueId != 0 && string.IsNullOrEmpty(sGitLabMilestone.LabelToAdd) == false)
                {
                    // add label to Issue
                    //NWDLogger.WriteLine("sGitLabMilestone.IssueId = " + sGitLabMilestone.IssueId + " LabelToAdd " + sGitLabMilestone.LabelToAdd);
                    GitLabClient tGitlabClient = new GitLabClient(tModel.GitUrl, tModel.GitToken);
                    var tIssue = await tGitlabClient.Issues.GetAsync(tModel.GitProject, sGitLabMilestone.IssueId);
                    if (tIssue != null)
                    {
                        if (tIssue.Labels.Contains(sGitLabMilestone.LabelToAdd) == false)
                        {
                            tIssue.Labels.Add(sGitLabMilestone.LabelToAdd);
                            UpdateIssueRequest tRequest = new UpdateIssueRequest();
                            tRequest.Labels = tIssue.Labels;
                            await tGitlabClient.Issues.UpdateAsync(tModel.GitProject, sGitLabMilestone.IssueId, tRequest);
                        }
                    }
                }
                if (sGitLabMilestone.IssueId != 0 && string.IsNullOrEmpty(sGitLabMilestone.LabelToRemove) == false)
                {
                    // remove label to Issue
                    GitLabClient tGitlabClient = new GitLabClient(tModel.GitUrl, tModel.GitToken);
                    var tIssue = await tGitlabClient.Issues.GetAsync(tModel.GitProject, sGitLabMilestone.IssueId);
                    if (tIssue != null)
                    {
                        if (tIssue.Labels.Contains(sGitLabMilestone.LabelToRemove) == true)
                        {
                            tIssue.Labels.Remove(sGitLabMilestone.LabelToRemove);
                            UpdateIssueRequest tRequest = new UpdateIssueRequest();
                            tRequest.Labels = tIssue.Labels;
                            await tGitlabClient.Issues.UpdateAsync(tModel.GitProject, sGitLabMilestone.IssueId, tRequest);
                        }
                    }
                }
                if (string.IsNullOrEmpty(sGitLabMilestone.Name) == false)
                {
                    sGitLabMilestone.GitLabProject = tModel;
                    await sGitLabMilestone.Prepare(sGitLabMilestone.SecretToken, null, null);
                    List<NWDGitLabMilestoneModel> tGitLabMilestoneModelList = new List<NWDGitLabMilestoneModel>();
                    tGitLabMilestoneModelList.Add(sGitLabMilestone);
                    ViewData.Add(nameof(NWDGitLabMilestoneModel), tGitLabMilestoneModelList);
                }
                else
                {
                    NWDGitLabMilestonesListModel tGitLabMilestoneList = await NWDGitLabMilestonesListModel.Prepare(sGitLabMilestone.SecretToken,HttpContext);
                    ViewData.Add(nameof(NWDGitLabMilestonesListModel), tGitLabMilestoneList);
                }
            }
            return View("/Views/NWDGitLabReport/Index.cshtml");
        }

        // public IActionResult Indexd()
        // {
        //     List<string> tList = new List<string>();
        //     string tError = tList[tList.Count];
        //     return View("/Views/NWDGitLabReport/Index.cshtml");
        // }

        //[HttpPost]
        //public async Task<IActionResult> Commit(NWDGitLabCommitModel sGitLabCommit)
        //{
        //    //NWDLogger.WriteLine("sGitLabCommit Hash : " + sGitLabCommit.Hash);
        //    GitLabProjectModel tModel = GitLabProjectModel.GetBySecretToken(sGitLabCommit.LocalTokenReport);
        //    if (tModel != null)
        //    {
        //        NWDProject tProject = NWDAppProjectExtension.GetByReference(tModel.Project);
        //        ViewData.Add(nameof(NWDProject), tProject);
        //        //ViewData.Add(nameof(GitLabProjectModel), tModel);
        //        ViewData.Add("Title", tModel.Name);
        //        try
        //        {
        //            GitLabClient tGitlabClient = new GitLabClient(tModel.GitUrl, tModel.GitToken);

        //            NWDGitLabMilestonesListModel tGitLabMilestoneList = await NWDGitLabMilestonesListModel.Prepare(tModel.LocalTokenReport);
        //            NWDGitLabMilestoneModel sGitLabMilestone = null;
        //            GitLabApiClient.Models.Commits.Responses.Commit tCommit = await tGitlabClient.Commits.GetAsync(tModel.GitProject, sGitLabCommit.Hash);
        //            //NWDLogger.WriteLine("tCommit.CommittedDate : " + tCommit.CommittedDate.ToLongDateString());

        //            foreach (NWDGitLabMilestoneModel sMilestone in tGitLabMilestoneList.MilestonesList)
        //            {
        //                //NWDLogger.WriteLine("sMilestone : " + sMilestone.Start.ToLongDateString() + " -> " + sMilestone.Due.ToLongDateString());
        //                if (sMilestone.Start.Date <= tCommit.CommittedDate.Date && sMilestone.Due.Date >= tCommit.CommittedDate.Date)
        //                {
        //                    sGitLabMilestone = sMilestone;
        //                    break;
        //                }
        //            }
        //            if (sGitLabMilestone != null)
        //            {
        //                sGitLabMilestone.GitLabProject = tModel;

NWDNuGet/NWDWebGitLabReport/Views/NWDGitLabReport/Commit.cshtml
@using Microsoft.AspNetCore.Http;
@using GitLabApiClient;
@using ChartJSCore.Models;
@using GitLabApiClient.Models.Commits.Responses;
@using NWDWebGitLabReport.Models
@{
    @*MyChart tChart = null;*@
    List<NWDGitLabMilestoneModel>? tGitLabMilestoneModelList = ViewData[nameof(NWDGitLabMilestoneModel)] as List<NWDGitLabMilestoneModel>;
    NWDGitLabMilestonesListModel? tGitLabMilestoneList = ViewData[nameof(NWDGitLabMilestonesListModel)] as NWDGitLabMilestonesListModel;
    @*if (tGitLabMilestone != null)
        {
            tChart = tGitLabMilestone.myChart;
        }*@
}
<h1 class="display-4">GitLab</h1>


@*<form action="/GitLab/Commit" method="post" id="CommitForm">
        @Html.Hidden(nameof(NWDGitLabMilestoneModel.Name), tGitLabMilestone.Name)
        <input type="submit" value="refresh" />
    </form>
    <script type="text/javascript">


            window.onload = function () {
                var counter = 5;
                var interval = setInterval(function () {
                    counter--;
                    $("#seconds").text(counter);
                    if (counter == 0) {
                        redirect();
                        clearInterval(interval);
                    }
                }, 1000);

            };

        function redirect() {
            document.onreadystatechange = function () {
                var tForm = document.getElementById("CommitForm");
                tForm.submit();
            }
        }
    </script>*@

@if (tGitLabMilestoneList != null)
{
    @model NWDWebGitLabReport.Models.NWDGitLabMilestoneModel
    @foreach (NWDGitLabMilestoneModel tM in tGitLabMilestoneList.MilestonesList)
    {
        @using (Html.BeginForm("Index", "NWDGitLabReport"))
        {
            @Html.Hidden(nameof(NWDGitLabMilestoneModel.Name), tM.Name)
            <input type="submit" value="Milestone @tM.Name @tM.Start.ToString("yyyy/MM/dd") - @tM.Due.ToString("yyyy/MM/dd")"/>
        }
    }
}

@if (tGitLabMilestoneModelList != null)
{
    foreach (NWDGitLabMilestoneModel tGitLabMilestone in tGitLabMilestoneModelList)
    {
        <div>


            @if (tGitLabMilestone != null)
            {
                <h4>Milestone @tGitLabMilestone.Name</h4>
                <div>
                    @if (tGitLabMilestone.MyMilestone != null)
                    {
                        <a href="@tGitLabMilestone.MyMilestone.WebUrl">View Milestone @tGitLabMilestone.Name on GitLab</a>
                        <div>
                            @tGitLabMilestone.MyMilestone.Description
                        </div>

                        <div>
                            <div>
                                Planning Poker total @tGitLabMilestone.TaskScoreTotal points!
                                @if (tGitLabMilestone.Pokers != null)
                                {
                                    foreach (string tP in tGitLabMilestone.Pokers)
                                    {
                                        <span> @tP</span>
                                    }
                                }
                            </div>
                            @if (tGitLabMilestone.StopAtCommit == null)
                            {
                                @if (tGitLabMilestone.MyMilestone.StartDate != null)
                                {
                                    <div> Start date at @tGitLabMilestone.MyMilestone.StartDate</div>
                                }
                                @if (tGitLabMilestone.MyMilestone.DueDate != null)
                                {
                                    <div> Due date at @tGitLabMilestone.MyMilestone.DueDate</div>
                                }
                                <div> Days to release @tGitLabMilestone.AvailableDays days!</div>
                            }
                            else
                            {
                                <div> Commit @tGitLabMilestone.StopAtCommit.ShortId</div>
                            }
                            @if (tGitLabMilestone.IssuesList != null)
                            {
                                <div>
                                    Task in milestone @tGitLabMilestone.IssuesList.Count
                                    <ul>
                                        @foreach (GitLabApiClient.Models.Issues.Responses.Issue tIssue in tGitLabMilestone.IssuesList)
                                        {
                                            <li class="closed">
                                                <a href="@tIssue.WebUrl">
                                                    <b>#@tIssue.Iid </b>
                                                </a> @tIssue.Title
                                                @foreach (string tIssueStr in tIssue.Labels)
                                                {
                                                    <span style="font-size: 12px; padding-right: 10px; padding-left: 10px; margin-left: 10px; border-radius: 12px; background-color: @tGitLabMilestone.LabelsDicoColor?[tIssueStr];"> @tIssueStr</span>
                                                }
                                            </li>
                                        }
                                    </ul>
                                </div>
                            }
                        </div>
                        <div class="page-layout">
                            <div class="div-float">
                                <h2>Burndown Chart</h2>
                                <canvas id="BurndownChart"></canvas>
                            </div>
                        </div>
                        <div class="page-layout">
                            <div class="div-float">
                                <h2>Task Chart</h2>
                                <canvas id="TaskChart"></canvas>
                            </div>
                        </div>
                        <div class="page-layout">
                            <div class="div-float">
                                <h2>Task State Chart</h2>
                                <canvas id="TaskStateChart"></canvas>
                            </div>
                        </div>
                        <script src="~/js/Chart/chart.js"></script>
                        <script type="text/javascript">
        @Html.Raw(tGitLabMilestone.BurndownGraph?.CreateChartCode("BurndownChart"));
        @Html.Raw(tGitLabMilestone.TasksGraph?.CreateChartCode("TaskChart"));
        @Html.Raw(tGitLabMilestone.TasksStateGraph?.CreateChartCode("TaskStateChart"));
                            </script>
                    }
                </div>
            }
        </div>
    }
}